### ISSUE TITLE
CephOSD ansible artifact space usage

### ISSUE THREAD

**Issue by dswebbthg** [elemental-lf/ceph-osd-operator#1]
I'm using the ceph-osd-operator with your ceph-with-helm setup, but am running into an issue with the operator filling up it's bind mount with artifacts from the ansible runs:

/dev/dm-14                 10G   10G  164K 100% /var/lib/docker/devicemapper/mnt/280038d2fcf320553302f798f2abf6bddcd8de8513296d6f439d8435d6242352

130 ✗ gb4-li-cephosd-002  /var/lib/docker/devicemapper/mnt/280038d2fcf320553302f798f2abf6bddcd8de8513296d6f439d8435d6242352/rootfs/tmp/ansible-operator/runner/ceph.elemental.
net/v1alpha1/CephOSD/ceph/ceph-osds/artifacts # ls |wc -l
3670

# du -sh ../artifacts/
9.5G	../artifacts/

# du -sh 5214328452333186070/*
1.6M	5214328452333186070/job_events
4.0K	5214328452333186070/rc
4.0K	5214328452333186070/status
1.1M	5214328452333186070/stdout

I'm currently "fixing" the issue by deleting the pod and having it recreated, but it would be good if it cleaned up after itself.

**Comment by elemental-lf** [comment]
Oh, sorry, for not responding. I still keep missing these GitHub notifications.
Regarding your issue I've also noticed this and AFAIK newer versions of the operator SDK have implemented a solution for this or they were at least discussing it at the time I last looked. Later this year (probably September) I will look into updating the dependencies of `ceph-osd-operator`. Before that I'll be moving the Helm charts first to the latest version of Ceph Mimic and after that to Nautilus. That's planned for August. I'll also look into cross porting anything useful from the Openstack charts if things haven't diverged too much.

**Comment by elemental-lf** [comment]
I'm going to close this. Ansible logfiles accumulating in the container hasn't been an issue for quite some time now.
